name: Auto Commit
on:
  push:
    paths:
      - 'data/inbox.json' # Triggas när du uppdaterar din inbox

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Process Data
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data/inbox.json
          git commit -m "Auto-processed inbox update"
          git push
